export type ButtonSize = 'small' | 'normal' | 'xnormal' | 'big'
export type ButtonColor = 'primary' | 'success' | 'warning' | 'error'
export type ButtonWeight = 'normal' | 'bold' | '500'
export type ButtonType = 'normal' | 'default' | 'outline' | 'ghost' | 'transparent'
export type ButtonRound = 'true' | 'false'
