export { Input, InputPassword, InputTextArea, InputNumber } from './Input.styles'
export { InputBigNumber } from './InputBigNumber'
export { InputPassword as InputPasswordTW } from './InputPassword'
export { InputSearch } from './InputSearch'
export * from './Input.types'
